linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - cyclop
    - decorder
    # - depguard
    - dogsled
    # - dupl   # Probably useful in principle. But did not find an easy way.
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustruct   # Should be useful in the future. No time now
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen  # Should be usefull in the future. No time atm
    # - gci  # Broken for me
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    # - gocognit  # Similar to cyclop. Could be usefull
    - goconst
    - gocritic
    # - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    # - gofumpt
    - goheader
    # - goimports
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    # - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    # - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen  # Usefull for the future
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint
  disable:
    - cyclop
    - depguard
    - dupl   # Probably useful in principle. But did not find an easy way.
    - exhaustruct   # Should be useful in the future. No time now
    - funlen  # Should be usefull in the future. No time atm
    - gci  # Broken for me
    - gocognit  # Similar to cyclop. Could be usefull
    - gocyclo
    # - gofmt
    - gofumpt
    - goimports
    - gomnd
    - maintidx  # Probably super usefull in the future
    - nestif
    - tagliatelle
    - varnamelen  # Usefull for the future
    - wsl
