"""Module for constants in Counter-Strike 2."""

# Sides
CT_SIDE = "ct"
T_SIDE = "t"

# Server
DEFAULT_SERVER_TICKRATE = 128

# Rounds
DEFAULT_FREEZE_TIME_IN_SECS = 20.0
DEFAULT_ROUND_TIME_IN_SECS = 115.0
DEFAULT_BOMB_TIME_IN_SECS = 40.0

# Grenades
DEFAULT_SMOKE_DURATION_IN_SECS = 20.0
DEFAULT_INFERNO_DURATION_IN_SECS = 7.03125

# Movement
RUNNING_SPEED = 250
GRAVITY = 800
CROUCHING_SPEED = 85
CROUCHING_ATTRIBUTE_FLAG = 65536
JUMP_HEIGHT = 65
# 0.5m * v^2 = m * g * h
# v = sqrt(2 * g * h)  # noqa: ERA001
JUMP_SPEED = (2 * GRAVITY * JUMP_HEIGHT) ** 0.5
