[package]
name = "awpy-python"
version.workspace = true
rust-version.workspace = true
edition = "2024"
license = "MIT"
publish = false

[lib]
name = "_awpy"
crate-type = ["cdylib"]

[dependencies]
awpy = { workspace = true }
awpy-proto = { workspace = true }
prost = "0.14"
pyo3 = { version = "0.27", features = ["extension-module"] }
pyo3-polars = "0.26"
polars = { version = "0.53", features = ["dtype-full"] }
