from enum import Enum


class RoundEndReason(Enum):
    """RoundEndReasons"""

    STILL_IN_PROGRESS = 0
    TARGET_BOMBED = 1
    VIP_ESCAPED = 2
    VIP_KILLED = 3
    TERRORISTS_ESCAPED = 4
    CT_STOPPED_ESCAPE = 5
    TERRORISTS_STOPPED = 6
    BOMB_DEFUSED = 7
    CT_WIN = 8
    TERRORISTS_WIN = 9
    DRAW = 10
    HOSTAGES_RESCUED = 11
    TARGET_SAVED = 12
    HOSTAGES_NOT_RESCUED = 13
    TERRORISTS_NOT_ESCAPED = 14
    VIP_NOT_ESCAPED = 15
    GAME_START = 16
    TERRORISTS_SURRENDER = 17
    CT_SURRENDER = 18
    TERRORISTS_PLANTED = 19
    CTS_REACHED_HOSTAGE = 20
